"""
generate_data.py
Generates 60 historical consulting projects organised into 6 coherent
scenario clusters. Each cluster shares a realistic distress pattern so
k-NN vector search returns meaningful, non-obvious matches.

Cluster A — Fintech / delivery / scope creep
Cluster B — Healthcare / delivery / team burnout
Cluster C — Retail / design / client sentiment drop
Cluster D — Logistics / stabilisation / budget overrun
Cluster E — Public sector / discovery / velocity drop
Cluster F — Insurance / closeout / late scope change
"""

import random
import numpy as np
from datetime import date, timedelta
from elasticsearch import Elasticsearch
from dotenv import load_dotenv
import os

load_dotenv()

ES_URL     = os.getenv("ES_URL")
ES_API_KEY = os.getenv("ES_API_KEY")
ES_USER    = os.getenv("ES_USERNAME", "elastic")
ES_PASS    = os.getenv("ES_PASSWORD", "changeme")

es = (
    Elasticsearch(ES_URL, api_key=ES_API_KEY)
    if ES_API_KEY
    else Elasticsearch(ES_URL, basic_auth=(ES_USER, ES_PASS))
)

random.seed(42)
np.random.seed(42)

PHASES = ["discovery", "design", "delivery", "stabilisation", "closeout"]


# ── Fingerprint ───────────────────────────────────────────────────────────────
def make_fingerprint(burn, velocity, sentiment, phase, team, tenure, milestone, margin):
    return [
        float(np.clip(burn,           -1, 1)),
        float(np.clip(velocity,       -1, 1)),
        float(np.clip(sentiment,      -1, 1)),
        float(PHASES.index(phase) / (len(PHASES) - 1)),
        float(min(team / 20,          1.0)),
        float(min(tenure / 36,        1.0)),
        float(min(milestone / 60,     1.0)),
        float(np.clip(margin / 50,    -1, 1)),
    ]


def jitter(value, noise=0.08):
    """Add small random noise to keep cluster members realistic but distinct."""
    return round(value + random.uniform(-noise, noise), 3)


def rand_date():
    start = date(2022, 1, 1)
    return (start + timedelta(days=random.randint(0, 900))).isoformat()


# ── Cluster definitions ───────────────────────────────────────────────────────
# Each cluster defines the "centre" of a distress pattern.
# Individual projects are generated by adding jitter around the centre.

CLUSTERS = [

    # ── A: Fintech / delivery / scope creep ──────────────────────────────────
    # Pattern: high burn acceleration, moderate velocity drop, mild sentiment drop
    # Most projects escalated because scope kept expanding without client sign-off
    {
        "id": "A",
        "industry": "fintech",
        "phase": "delivery",
        "team_size_range": (7, 12),
        "tenure_range": (10, 20),
        "milestone_range": (12, 25),
        "burn": 0.58,
        "velocity": -0.38,
        "sentiment": -0.52,
        "margin": 34.0,
        "projects": [
            ("Apex Capital Core Banking Overhaul",        "escalated",       "client_escalation",      -22.4, 5),
            ("Meridian Payments Platform Migration",      "escalated",       "scope_renegotiation",    -18.7, 4),
            ("Quantum Fintech Data Warehouse",            "rescued",         "exec_intervention",       -9.2, 3),
            ("NovaTrade Settlement Engine Rebuild",       "escalated",       "client_escalation",      -25.1, 6),
            ("BlueStar Regulatory Reporting System",      "escalated",       "scope_renegotiation",    -20.3, 5),
            ("Vertex FX Trading Platform Upgrade",        "rescued",         "internal_reallocation",  -11.4, 4),
            ("ClearPath Lending Decisioning Engine",      "escalated",       "client_escalation",      -28.9, 7),
            ("Pinnacle Wealth Management Portal",         "lost",            "exec_intervention",      -41.2, 8),
            ("TrueNorth AML Compliance Platform",         "escalated",       "scope_renegotiation",    -19.6, 5),
            ("Cobalt Digital Banking Transformation",     "rescued",         "exec_intervention",       -8.8, 3),
        ],
    },

    # ── B: Healthcare / delivery / team burnout ───────────────────────────────
    # Pattern: moderate burn, steep velocity drop, stable sentiment (client unaware)
    # Most rescued via internal reallocation — team was overloaded, not scope issue
    {
        "id": "B",
        "industry": "healthcare",
        "phase": "delivery",
        "team_size_range": (4, 9),
        "tenure_range": (18, 48),
        "milestone_range": (15, 35),
        "burn": 0.31,
        "velocity": -0.55,
        "sentiment": -0.18,
        "margin": 22.0,
        "projects": [
            ("NHS Patient Record Integration",            "rescued",         "internal_reallocation",   -7.1, 3),
            ("MedCore Clinical Data Platform",            "rescued",         "internal_reallocation",   -6.4, 2),
            ("HealthFirst EHR Migration",                 "rescued",         "team_augmentation",       -9.8, 4),
            ("Caduceus Lab Systems Modernisation",        "escalated",       "client_escalation",      -17.2, 5),
            ("Meridian Hospital Analytics Rollout",       "rescued",         "internal_reallocation",   -5.9, 3),
            ("PulseHealth Remote Monitoring Platform",    "rescued",         "internal_reallocation",   -8.3, 3),
            ("CareSync Pharmacy Integration",             "rescued",         "team_augmentation",       -7.7, 4),
            ("VitalPath Oncology Data Hub",               "escalated",       "exec_intervention",      -14.6, 5),
            ("Helix Genomics Data Pipeline",              "rescued",         "internal_reallocation",   -6.1, 2),
            ("Spectrum Mental Health Platform",           "delivered_clean", "internal_reallocation",    2.1, 2),
        ],
    },

    # ── C: Retail / design / client sentiment drop ────────────────────────────
    # Pattern: low burn acceleration, mild velocity drop, steep sentiment drop
    # Client expectations misaligned early — design not matching vision
    {
        "id": "C",
        "industry": "retail",
        "phase": "design",
        "team_size_range": (3, 7),
        "tenure_range": (3, 14),
        "milestone_range": (20, 45),
        "burn": 0.18,
        "velocity": -0.22,
        "sentiment": -0.65,
        "margin": 18.0,
        "projects": [
            ("RetailMax Personalisation Engine",          "rescued",         "client_escalation",       -9.4, 4),
            ("FashionForward Omnichannel Platform",       "escalated",       "scope_renegotiation",    -16.8, 5),
            ("GreenLeaf Loyalty Programme Rebuild",       "rescued",         "exec_intervention",       -8.1, 3),
            ("SuperStore Supply Chain Visibility",        "escalated",       "client_escalation",      -19.3, 6),
            ("BrandCo Digital Experience Platform",       "rescued",         "scope_renegotiation",    -11.2, 4),
            ("TrendHub Merchandising Analytics",          "delivered_clean", "client_escalation",        1.8, 3),
            ("StylePoint POS Modernisation",              "escalated",       "scope_renegotiation",    -14.7, 5),
            ("CartPlus Checkout Optimisation",            "rescued",         "exec_intervention",       -7.6, 3),
            ("PrimeRetail Inventory Intelligence",        "lost",            "client_escalation",      -38.4, 9),
            ("LuxGoods CRM Implementation",               "escalated",       "scope_renegotiation",    -17.9, 6),
        ],
    },

    # ── D: Logistics / stabilisation / budget overrun ─────────────────────────
    # Pattern: very high burn, low velocity drop (team working hard, just expensive)
    # Most lost — by stabilisation phase, overruns are structural, not fixable
    {
        "id": "D",
        "industry": "logistics",
        "phase": "stabilisation",
        "team_size_range": (8, 16),
        "tenure_range": (6, 24),
        "milestone_range": (5, 18),
        "burn": 0.72,
        "velocity": -0.14,
        "sentiment": -0.31,
        "margin": 42.0,
        "projects": [
            ("FreightCore TMS Replacement",               "lost",            "exec_intervention",      -44.1, 9),
            ("RouteMax Last-Mile Optimisation",           "lost",            "scope_renegotiation",    -39.7, 8),
            ("HarbourLink Port Operations Platform",      "escalated",       "exec_intervention",      -28.3, 7),
            ("FleetPro Vehicle Telemetry System",         "lost",            "timeline_extension",     -46.8, 10),
            ("CargoSync Customs Compliance Platform",     "rescued",         "exec_intervention",      -18.4, 5),
            ("NexRoute Warehouse Automation",             "lost",            "scope_renegotiation",    -41.2, 9),
            ("SwiftFreight Carrier Integration",          "escalated",       "client_escalation",      -31.6, 7),
            ("PeakLogistics Network Optimiser",           "lost",            "exec_intervention",      -48.3, 11),
            ("CrossBorder Trade Compliance System",       "escalated",       "timeline_extension",     -24.7, 6),
            ("DockMaster Yard Management Platform",       "lost",            "scope_renegotiation",    -43.9, 10),
        ],
    },

    # ── E: Public sector / discovery / velocity drop ──────────────────────────
    # Pattern: low burn, steep velocity drop, mild sentiment (bureaucratic slowdown)
    # Most rescued via timeline extension — procurement and approval delays fixable
    {
        "id": "E",
        "industry": "public sector",
        "phase": "discovery",
        "team_size_range": (3, 8),
        "tenure_range": (2, 12),
        "milestone_range": (25, 55),
        "burn": 0.14,
        "velocity": -0.48,
        "sentiment": -0.21,
        "margin": 15.0,
        "projects": [
            ("HMRC Digital Tax Service",                  "rescued",         "timeline_extension",      -5.8, 3),
            ("DWP Benefits Processing Platform",          "rescued",         "timeline_extension",      -4.9, 2),
            ("NHS Digital Appointment System",            "rescued",         "internal_reallocation",   -6.7, 3),
            ("MOD Asset Tracking Platform",               "escalated",       "client_escalation",      -12.4, 5),
            ("Cabinet Office Data Integration",           "rescued",         "timeline_extension",      -5.1, 3),
            ("DVLA Vehicle Registration Modernisation",   "rescued",         "timeline_extension",      -4.3, 2),
            ("Environment Agency Monitoring Platform",    "delivered_clean", "timeline_extension",       1.4, 2),
            ("CPS Case Management System",                "escalated",       "exec_intervention",      -11.8, 5),
            ("Land Registry Digital Transformation",     "rescued",         "timeline_extension",      -6.2, 3),
            ("Ofsted Inspection Platform",                "rescued",         "internal_reallocation",   -5.4, 2),
        ],
    },

    # ── F: Insurance / closeout / late scope change ───────────────────────────
    # Pattern: moderate burn spike, moderate velocity drop, steep sentiment drop
    # Mixed outcomes — late scope changes sometimes recoverable, sometimes fatal
    {
        "id": "F",
        "industry": "insurance",
        "phase": "closeout",
        "team_size_range": (4, 10),
        "tenure_range": (12, 36),
        "milestone_range": (3, 12),
        "burn": 0.44,
        "velocity": -0.33,
        "sentiment": -0.47,
        "margin": 28.0,
        "projects": [
            ("Aviva Claims Automation Platform",          "rescued",         "scope_renegotiation",     -9.7, 3),
            ("LloydsRe Reinsurance Data Hub",             "escalated",       "client_escalation",      -21.4, 6),
            ("SunLife Policy Administration System",      "rescued",         "exec_intervention",       -8.3, 3),
            ("TowerBridge Underwriting Platform",         "lost",            "scope_renegotiation",    -36.9, 8),
            ("EagleStar Actuarial Modelling Tool",        "rescued",         "scope_renegotiation",    -11.2, 4),
            ("ShieldMutual Claims Portal Upgrade",        "escalated",       "client_escalation",      -18.7, 5),
            ("NorthStar Compliance Reporting System",     "rescued",         "exec_intervention",       -7.8, 3),
            ("HorizonLife Pension Administration",        "delivered_clean", "scope_renegotiation",      2.4, 2),
            ("MarbleCo Fraud Detection Platform",         "escalated",       "timeline_extension",     -16.3, 5),
            ("RedRock Digital Broker Portal",             "lost",            "client_escalation",      -42.1, 9),
        ],
    },
]


# ── Generate docs from clusters ───────────────────────────────────────────────
def generate_all() -> list[dict]:
    docs = []
    project_num = 1

    for cluster in CLUSTERS:
        team_min, team_max       = cluster["team_size_range"]
        tenure_min, tenure_max   = cluster["tenure_range"]
        milestone_min, milestone_max = cluster["milestone_range"]

        for name, outcome, intervention, margin_impact, weeks in cluster["projects"]:
            team     = random.randint(team_min, team_max)
            tenure   = random.randint(tenure_min, tenure_max)
            milestone = random.randint(milestone_min, milestone_max)

            # Jitter the cluster centre signals
            burn      = jitter(cluster["burn"],      noise=0.10)
            velocity  = jitter(cluster["velocity"],  noise=0.10)
            sentiment = jitter(cluster["sentiment"], noise=0.08)
            margin    = round(jitter(cluster["margin"], noise=4.0), 1)

            # Worse outcomes have slightly worse signals
            severity_boost = {"lost": 0.12, "escalated": 0.06, "rescued": 0.0, "delivered_clean": -0.05}[outcome]
            burn      = round(min(burn + severity_boost, 0.95), 3)
            velocity  = round(max(velocity - severity_boost, -0.95), 3)
            sentiment = round(max(sentiment - severity_boost * 0.5, -0.95), 3)

            fp = make_fingerprint(
                burn, velocity, sentiment,
                cluster["phase"], team, tenure, milestone, margin
            )

            docs.append({
                "project_id":             f"HIST-{project_num:03d}",
                "project_name":           name,
                "industry":               cluster["industry"],
                "phase_at_detection":     cluster["phase"],
                "cluster":                cluster["id"],
                "team_size":              team,
                "client_tenure_months":   tenure,
                "days_to_milestone":      milestone,
                "burn_rate_acceleration": burn,
                "velocity_delta":         velocity,
                "sentiment_slope":        sentiment,
                "margin_at_risk_pct":     margin,
                "intervention":           intervention,
                "outcome":                outcome,
                "margin_impact_pct":      margin_impact,
                "weeks_to_resolution":    weeks,
                "partner_overrode_agent": random.random() < 0.15,
                "notes":                  f"Cluster {cluster['id']} — {cluster['industry']} {cluster['phase']} pattern",
                "closed_date":            rand_date(),
                "fingerprint":            fp,
            })
            project_num += 1

    return docs


# ── Bulk index ────────────────────────────────────────────────────────────────
def bulk_index(index: str, docs: list[dict], id_field: str):
    operations = []
    for doc in docs:
        operations.append({"index": {"_index": index, "_id": doc[id_field]}})
        operations.append(doc)
    resp   = es.bulk(operations=operations)
    errors = [i for i in resp["items"] if "error" in i.get("index", {})]
    print(f"  {index}: {len(docs) - len(errors)}/{len(docs)} indexed" +
          (f" | {len(errors)} errors" if errors else ""))


# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n=== Generating clustered historical project data ===\n")
    info = es.info()
    print(f"Connected: {info['cluster_name']} (v{info['version']['number']})\n")

    # Delete and re-create to avoid stale data
    if es.indices.exists(index="projects_historical"):
        es.indices.delete(index="projects_historical")
        print("  Deleted existing projects_historical index")
    es.indices.create(index="projects_historical")
    print("  Re-created projects_historical index\n")

    docs = generate_all()

    print(f"Indexing {len(docs)} projects across 6 clusters...")
    bulk_index("projects_historical", docs, "project_id")

    # Cluster summary
    print("\nCluster breakdown:")
    for cluster_id in ["A", "B", "C", "D", "E", "F"]:
        cluster_docs = [d for d in docs if d["cluster"] == cluster_id]
        outcomes = {}
        for d in cluster_docs:
            outcomes[d["outcome"]] = outcomes.get(d["outcome"], 0) + 1
        desc = {
            "A": "Fintech / delivery / scope creep",
            "B": "Healthcare / delivery / team burnout",
            "C": "Retail / design / sentiment drop",
            "D": "Logistics / stabilisation / budget overrun",
            "E": "Public sector / discovery / velocity drop",
            "F": "Insurance / closeout / late scope change",
        }[cluster_id]
        print(f"  Cluster {cluster_id} ({desc}): {outcomes}")

    count = es.count(index="projects_historical")["count"]
    print(f"\nTotal: {count} historical projects indexed")
    print("\nExpected k-NN behaviour:")
    print("  LIVE-001 (fintech, delivery) -> should match Cluster A projects")
    print("  Run orchestrator.py to verify\n")
